package br.com.conductor.messages.ui;

/**
 *
 * @author Felipe Brito
 */
public class LoadingUI extends javax.swing.JDialog {

    private static final long serialVersionUID = 5803992921370023168L;

    /**
     * Creates new form LoadingUI
     */
    public LoadingUI() {
        initComponents();
    }

    private void initView() {
//        lblImagemLoading.setIcon(new ImageIcon(getClass().getResource("/loading.gif")));
    }

    public void showView() {
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setModal(true);
        initView();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblImagemLoading = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(145, 128));

        lblImagemLoading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImagemLoading.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loading.gif"))); // NOI18N
        lblImagemLoading.setPreferredSize(new java.awt.Dimension(145, 128));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblImagemLoading, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblImagemLoading, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblImagemLoading;
    // End of variables declaration//GEN-END:variables
}
